theme = "onedark"

[editor]
scrolloff = 999
line-number = "relative"
path-completion = true
rulers = [88]
default-line-ending = "lf"
insert-final-newline = true

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "block"

[editor.file-picker]
hidden = true
ignore = true
git-ignore = false

[editor.soft-wrap]
enable = true
max-wrap = 25

[editor.inline-diagnostics]
cursor-line = "info"

[keys.normal]
C-g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]
d = "delete_selection_noyank"
A-d = "delete_selection"
