[[language]]
name = "python"
language-id = "python"
file-types = ["py"]
roots = [".", "pixi.toml", "setup.py", "pyproject.toml", "setup.py"]
auto-format = true
language-servers = [ "basedpyright", "ruff", "codebook", "pyrefly" ]
formatter = { command = "ruff", args = ["format", "-"] }

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
"'" = "'"
'`' = '`'
'<' = '>'

[[language]]
name = "rust"
language-id = "rust"
language-servers = [ "rust-analyzer" ]

[[language]]
name = "markdown"
language-id = "markdown"
language-servers = ["marksman", "codebook", "markdown-oxide"]

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
"'" = "'"
'<' = '>'

[[language]]
name = "bash"

[[language]]
name = "bibtex"

[[language]]
name = "html"

[[language]]
name = "javascript"

[[language]]
name = "typescript"

[[language]]
name = "mojo"
language-servers = [ "mojo-lsp-server", "codebook" ]

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
"'" = "'"
'`' = '`'
'<' = '>'

[[language]]
name = "latex"

[[language]]
name = "typst"
language-servers = ["tinymist", "codebook"]

[[language]]
name = "yaml"

[language-server.basedpyright]
command = "basedpyright-langserver"
args = ["--stdio"]
except-features = ["format", "code-action"]

[language-server.basedpyright.config.basedpyright.analysis]
autoSearchPaths = true
typeCheckingMode = "basic"
diagnosticMode = "openFilesOnly"

[language-server.ruff]
command = "ruff"
args = ["server"]

[language-server.codebook]
command = "codebook-lsp"
args = [ "serve" ]

[language-server.pyrefly]
command = "pyrefly"
args = ["lsp"]

[language-server.markdown-oxide]
command = "markdown-oxide"

[language-server.mojo-lsp-server]
command = "mojo-lsp-server"
args = [ "-I", "src/" ]
